
package com.daehosting.webservices.isbn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * DataFlex Web Service to validate ISBN numbers.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISBNService", targetNamespace = "http://webservices.daehosting.com/ISBN", wsdlLocation = "http://webservices.daehosting.com/services/isbnservice.wso?WSDL")
public class ISBNService
    extends Service
{

    private final static URL ISBNSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISBNSERVICE_EXCEPTION;
    private final static QName ISBNSERVICE_QNAME = new QName("http://webservices.daehosting.com/ISBN", "ISBNService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.daehosting.com/services/isbnservice.wso?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISBNSERVICE_WSDL_LOCATION = url;
        ISBNSERVICE_EXCEPTION = e;
    }

    public ISBNService() {
        super(__getWsdlLocation(), ISBNSERVICE_QNAME);
    }

    public ISBNService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISBNSERVICE_QNAME, features);
    }

    public ISBNService(URL wsdlLocation) {
        super(wsdlLocation, ISBNSERVICE_QNAME);
    }

    public ISBNService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISBNSERVICE_QNAME, features);
    }

    public ISBNService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISBNService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISBNServiceSoapType
     */
    @WebEndpoint(name = "ISBNServiceSoap")
    public ISBNServiceSoapType getISBNServiceSoap() {
        return super.getPort(new QName("http://webservices.daehosting.com/ISBN", "ISBNServiceSoap"), ISBNServiceSoapType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISBNServiceSoapType
     */
    @WebEndpoint(name = "ISBNServiceSoap")
    public ISBNServiceSoapType getISBNServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.daehosting.com/ISBN", "ISBNServiceSoap"), ISBNServiceSoapType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISBNSERVICE_EXCEPTION!= null) {
            throw ISBNSERVICE_EXCEPTION;
        }
        return ISBNSERVICE_WSDL_LOCATION;
    }

}
