
package com.daehosting.webservices.isbn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISBNServiceSoapType", targetNamespace = "http://webservices.daehosting.com/ISBN")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISBNServiceSoapType {


    /**
     * The test is done by calculation on the first 12 digits and compare the result with the checksum number at the end. You have to pass a 13 digits number.
     * 
     * @param sISBN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsValidISBN13")
    @WebResult(name = "IsValidISBN13Result", targetNamespace = "http://webservices.daehosting.com/ISBN")
    @RequestWrapper(localName = "IsValidISBN13", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN13")
    @ResponseWrapper(localName = "IsValidISBN13Response", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN13Response")
    public boolean isValidISBN13(
        @WebParam(name = "sISBN", targetNamespace = "http://webservices.daehosting.com/ISBN")
        String sISBN);

    /**
     * The test is done by calculation on the first 9 digits and compare the result with the checksum number at the end. You have to pass a 10 digits number or 8 digits and an X.
     * 
     * @param sISBN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsValidISBN10")
    @WebResult(name = "IsValidISBN10Result", targetNamespace = "http://webservices.daehosting.com/ISBN")
    @RequestWrapper(localName = "IsValidISBN10", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN10")
    @ResponseWrapper(localName = "IsValidISBN10Response", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN10Response")
    public boolean isValidISBN10(
        @WebParam(name = "sISBN", targetNamespace = "http://webservices.daehosting.com/ISBN")
        String sISBN);

}
